run:
  go: "1.23"
  concurrency: 8
  timeout: 5m
  build-tags:
    - mage

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - mock_.*\.go
    - magefile_test\.go
    - _scratch/.*\.go

linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused

linters-settings:
  misspell:
    locale: US
