version: 2

builds:
  - main: main.go
    binary: nextver
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
      - darwin
      - windows
    ldflags:
      - >-
        -X github.com/craftypath/nextver/cmd/nextver.Version={{ .Tag }}
        -X github.com/craftypath/nextver/cmd/nextver.GitCommit={{ .Commit }}
        -X github.com/craftypath/nextver/cmd/nextver.BuildDate={{ .Date }}
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - LICENSE
      - README.md
brews:
  - repository:
      owner: craftypath
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: craftypath-ci-bot
      email: craftypath-ci-bot@users.noreply.github.com
    directory: Formula
    homepage: https://github.com/craftypath/nextver/
    description: Automatic semver versioning
    test: |
      system "#{bin}/nextver --version"
